services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - red_seguridad

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file: .env
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - red_seguridad

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back_app
    restart: always
    env_file: .env
    ports:
      - "${BACKEND_PORT}:8081"
    depends_on:
      - postgres
    networks:
      - red_seguridad

networks:
  red_seguridad:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
